In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Convolution2D, MaxPooling2D, Flatten, Dropout,Conv2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

2024-12-19 17:33:10.643790: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-19 17:33:10.657618: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1734609790.674176   14070 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734609790.679225   14070 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-19 17:33:10.695772: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

In [3]:
x_train=train_datagen.flow_from_directory(directory="/home/shravya/Smart Mathematics Tutor/Dataset/train",target_size=(64,64),batch_size=32,class_mode='categorical')
x_test=train_datagen.flow_from_directory(directory="/home/shravya/Smart Mathematics Tutor/Dataset/test",target_size=(64,64),batch_size=32,class_mode='categorical')

Found 10941 images belonging to 3 classes.
Found 300 images belonging to 3 classes.


In [4]:
model=Sequential()

In [5]:
model.add(Conv2D(32,(3,3),input_shape=(64,64,3),activation='relu'))

/home/shravya/myenv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-12-19 17:33:12.789010: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [6]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [7]:
model.add(Conv2D(32,(3,3),activation='relu'))

In [8]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [9]:
model.add(Flatten())

In [10]:
model.add(Dense(32))

In [11]:
model.add(Dense(3,activation='softmax'))

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 62, 62, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 31, 31, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 29, 29, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 6272)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │       200,736 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 210,979 (824.14 KB)

 Trainable params: 210,979 (824.14 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [14]:
# Assuming you have already defined and compiled your model (e.g., `model`)

# Train the model using the generators
model.fit(
    x_train,                            # Train data generator
    steps_per_epoch=len(x_train),       # Number of batches per epoch
    epochs=5,                           # Number of epochs to train the model
    validation_data=x_test,             # Validation data generator
    validation_steps=len(x_test)        # Number of validation batches per epoch
)

/home/shravya/myenv/lib/python3.12/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/5
342/342 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.8877 - loss: 0.3202

/home/shravya/myenv/lib/python3.12/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


342/342 ━━━━━━━━━━━━━━━━━━━━ 25s 71ms/step - accuracy: 0.8879 - loss: 0.3196 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 2/5
342/342 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9992 - loss: 0.0051 - val_accuracy: 1.0000 - val_loss: 8.2609e-04
Epoch 3/5
342/342 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - accuracy: 0.9996 - loss: 0.0020 - val_accuracy: 1.0000 - val_loss: 0.0018
Epoch 4/5
342/342 ━━━━━━━━━━━━━━━━━━━━ 18s 51ms/step - accuracy: 0.9990 - loss: 0.0030 - val_accuracy: 1.0000 - val_loss: 1.1925e-04
Epoch 5/5
342/342 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9980 - loss: 0.0064 - val_accuracy: 1.0000 - val_loss: 3.0996e-04


In [16]:
model.save('shape.h5')

In [17]:
from tensorflow.keras.models import load_model
from keras.preprocessing import image
model=load_model("shape.h5")

In [18]:
img=image.load_img("/home/shravya/Smart Mathematics Tutor/Dataset/test/square/0.png",target_size=(64,64))

In [19]:
x=image.img_to_array(img)

In [20]:
x=np.expand_dims(x,axis=0)

In [22]:
pred=model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


In [23]:
pred

array([[0., 1., 0.]], dtype=float32)

In [26]:
# Assuming `pred` is the output from your model (a probability vector)
pred_class = np.argmax(pred[0])  # Get the class index with the highest probability

# Now, you can use the index to get the class name
index = ['circle', 'square', 'triangle']
result = index[pred_class]  # Get the class name corresponding to the predicted index

print(result)  # Output the predicted class name

square


In [31]:
img=image.load_img("/home/shravya/Smart Mathematics Tutor/Dataset/test/triangle/0.png",target_size=(64,64))
y=image.img_to_array(img)
y=np.expand_dims(y,axis=0)

In [32]:
pred=model.predict(y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


In [33]:
pred

array([[0., 0., 1.]], dtype=float32)

In [34]:
# Assuming `pred` is the output from your model (a probability vector)
pred_class = np.argmax(pred[0])  # Get the class index with the highest probability

# Now, you can use the index to get the class name
index = ['circle', 'square', 'triangle']
result = index[pred_class]  # Get the class name corresponding to the predicted index

print(result)  # Output the predicted class name

triangle


In [35]:
img=image.load_img("/home/shravya/Smart Mathematics Tutor/Dataset/test/circle/0.png",target_size=(64,64))
z=image.img_to_array(img)
z=np.expand_dims(z,axis=0)

In [36]:
pred=model.predict(z)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


In [37]:
pred

array([[1., 0., 0.]], dtype=float32)

In [38]:
# Assuming `pred` is the output from your model (a probability vector)
pred_class = np.argmax(pred[0])  # Get the class index with the highest probability

# Now, you can use the index to get the class name
index = ['circle', 'square', 'triangle']
result = index[pred_class]  # Get the class name corresponding to the predicted index

print(result)  # Output the predicted class name

circle
